DOMAIN = "felicity_solar"
BASE_URL = "https://shine-api.felicitysolar.com"
LOGIN_ENDPOINT = "/userlogin"
REFRESH_TOKEN_ENDPOINT = "/openApi/sec/refreshToken"
PLANT_LIST_ENDPOINT = "/plant/list_plant"
DEVICE_REALTIME_ENDPOINT = "/device/get_device_realtime_icon_template_info"
ORGAN_CODE = "100000100001100000100000100008"